on:
  push:
    paths: ["src/*"]
    branches: [master]

name: CI

jobs:
  build_matrix:
    strategy:
      matrix:
        build: [linux]
        include:
          - build: linux
            os: ubuntu-latest
            file: server_sync
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Strip files
        run: strip target/release/${{ matrix.file }}

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: PGen-${{ matrix.build }}
          path: target/release/${{ matrix.file }}
